RULES = [
    {
        "name": "addition",
        "pattern": [("KEYWORD", "add"), ("OPERAND", None), ("WORD", "and"), ("OPERAND", None)],
    },
    {
        "name": "subtraction",
        "pattern": [("KEYWORD", "subtract"), ("OPERAND", None), ("WORD", "from"), ("OPERAND", None)],
    },
    {
        "name": "multiplication",
        "pattern": [("KEYWORD", "multiply"), ("OPERAND", None), ("WORD", "and"), ("OPERAND", None)],
    },
    {
        "name": "division",
        "pattern": [("KEYWORD", "divide"), ("OPERAND", None), ("WORD", "by"), ("OPERAND", None)],
    },
    {
        "name": "modulo",
        "pattern": [("KEYWORD", "modulo"), ("OPERAND", None), ("WORD", "by"), ("OPERAND", None)],
    },
    {
        "name": "power",
        "pattern": [("KEYWORD", "power"), ("OPERAND", None), ("WORD", "to"), ("OPERAND", None)],
    },
    {
        "name": "print",
        "pattern": [("KEYWORD", "print"), ("OPERAND", None)],
    },
    {
        "name": "input",
        "pattern": [("KEYWORD", "input"), ("IDENTIFIER", None)],
    },
    {
        "name": "set_variable",
        "pattern": [("KEYWORD", "set"), ("IDENTIFIER", None), ("WORD", "to"), ("OPERAND", None)],
    },
    {
        "name": "increment",
        "pattern": [("KEYWORD", "increment"), ("IDENTIFIER", None)],
    },
    {
        "name": "decrement",
        "pattern": [("KEYWORD", "decrement"), ("IDENTIFIER", None)],
    },
    {
        "name": "minimum",
        "pattern": [
            ("KEYWORD", "minimum"),
            ("WORD", "of"),
            ("OPERAND", None),
            ("WORD", "and"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "maximum",
        "pattern": [
            ("KEYWORD", "maximum"),
            ("WORD", "of"),
            ("OPERAND", None),
            ("WORD", "and"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "if_greater",
        "pattern": [
            ("KEYWORD", "if"),
            ("OPERAND", None),
            ("WORD", "greater"),
            ("WORD", "than"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "if_greater_then_begin_print_else_begin_print",
        "pattern": [
            ("KEYWORD", "if"),
            ("OPERAND", None),
            ("WORD", "is"),
            ("WORD", "greater"),
            ("WORD", "than"),
            ("OPERAND", None),
            ("WORD", "then"),
            ("KEYWORD", "begin"),
            ("KEYWORD", "print"),
            ("OPERAND", None),
            ("KEYWORD", "end"),
            ("KEYWORD", "else"),
            ("KEYWORD", "begin"),
            ("KEYWORD", "print"),
            ("OPERAND", None),
            ("KEYWORD", "end"),
        ],
    },
    {
        "name": "if_less",
        "pattern": [
            ("KEYWORD", "if"),
            ("OPERAND", None),
            ("WORD", "less"),
            ("WORD", "than"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "if_equal",
        "pattern": [
            ("KEYWORD", "if"),
            ("OPERAND", None),
            ("WORD", "equal"),
            ("WORD", "to"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "if_equal_and_equal_then_print",
        "pattern": [
            ("KEYWORD", "if"),
            ("OPERAND", None),
            ("WORD", "is"),
            ("OPERAND", None),
            ("WORD", "and"),
            ("OPERAND", None),
            ("WORD", "is"),
            ("OPERAND", None),
            ("WORD", "then"),
            ("KEYWORD", "print"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "if_equal_or_equal_then_print",
        "pattern": [
            ("KEYWORD", "if"),
            ("OPERAND", None),
            ("WORD", "is"),
            ("OPERAND", None),
            ("WORD", "or"),
            ("OPERAND", None),
            ("WORD", "is"),
            ("OPERAND", None),
            ("WORD", "then"),
            ("KEYWORD", "print"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "if_not_equal",
        "pattern": [
            ("KEYWORD", "if"),
            ("OPERAND", None),
            ("WORD", "not"),
            ("WORD", "equal"),
            ("WORD", "to"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "if_greater_equal",
        "pattern": [
            ("KEYWORD", "if"),
            ("OPERAND", None),
            ("WORD", "greater"),
            ("WORD", "or"),
            ("WORD", "equal"),
            ("WORD", "to"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "if_less_equal",
        "pattern": [
            ("KEYWORD", "if"),
            ("OPERAND", None),
            ("WORD", "less"),
            ("WORD", "or"),
            ("WORD", "equal"),
            ("WORD", "to"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "if_else_greater_print",
        "pattern": [
            ("KEYWORD", "if"),
            ("OPERAND", None),
            ("WORD", "greater"),
            ("WORD", "than"),
            ("OPERAND", None),
            ("KEYWORD", "else"),
            ("KEYWORD", "print"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "while_greater",
        "pattern": [
            ("KEYWORD", "while"),
            ("OPERAND", None),
            ("WORD", "greater"),
            ("WORD", "than"),
            ("OPERAND", None),
        ],
    },
    {
        "name": "loop_times",
        "pattern": [("KEYWORD", "loop"), ("NUMBER", None), ("WORD", "times")],
    },
]
